import "./kiana.scss";
export { default as Switch } from "./Switch.vue";
export { default as Input } from "./Input.vue";
export { default as Button } from "./Button.vue";
export { default as Tabs } from "./Tabs/Tabs.vue";
export { default as Tab } from "./Tabs/Tab.vue";
export { default as Dialog } from "./Dialog/Dialog.vue";
export { openDialog as openDialog } from "./Dialog/openDialog";
export { default as Col } from "./Grid/Col.vue";
export { default as Row } from "./Grid/Row.vue";
export { default as Radio } from "./radio/Radio.vue";
export { default as kianaUI } from "./kianaUI";
